const UPDATE = "UPDATE"
const ADD = "ADD";
const SUBTRACT = "SUBTRACT";
const MULTIPLY = "MULTIPLY";
const DIVIDE = "DIVIDE";
const CLEAR = "CLEAR";
const EQUAL = "EQUAL";
const SIGN = "SIGN";
const SQUARE = "SQUARE";
const SQUARE_ROOT = "SQUARE_ROOT";

export { UPDATE, ADD, SUBTRACT, MULTIPLY, DIVIDE, CLEAR, EQUAL, SIGN, SQUARE, SQUARE_ROOT };